window.CLI_COURSE = window.CLI_COURSE || { modules: [], exam: null, cheatsheet: null };
window.CLI_COURSE.exam = {
  id: "exam", title: "Фінальний іспит", passPercent: 80,
  quiz: [
    { title: "Старт", question: "Ти вводиш `/compact keep the DB schema`. Що таке `keep the DB schema`?", options: ["Аргумент команди — інструкція, що зберегти в підсумку", "Окремий промпт для моделі", "Помилка синтаксису"], correct: 0, feedback: "Текст після назви slash-команди передається їй як аргумент." },
    { title: "Старт", question: "Звідки найнадійніше дізнатися, які команди є саме у твоїй версії Claude Code?", options: ["Зі статті в блозі", "З меню `/` або `/help`", "З `CLAUDE.md`"], correct: 1, feedback: "Набір команд залежить від версії, плану й платформи; меню показує реальний стан." },
    { title: "CLAUDE.md", question: "Команда постійно пояснює агенту, як запускати тести. Що зробити?", options: ["Записати команду тестів у проєктний `CLAUDE.md` і закомітити", "Щоразу копіювати інструкцію в промпт", "Вимкнути тести"], correct: 0, feedback: "`CLAUDE.md` читається на початку кожної сесії в усіх, хто працює з репозиторієм." },
    { title: "Режими", question: "Ти працюєш з чужим незнайомим кодом і хочеш, щоб агент нічого не міняв, доки ти не схвалиш план. Як почати?", options: ["`claude --dangerously-skip-permissions`", "`claude --permission-mode acceptEdits`", "`claude --permission-mode plan`"], correct: 2, feedback: "Режим `plan` блокує правки до схвалення плану." },
    { title: "Режими", question: "Що перемикає `Shift+Tab` у сесії Claude Code?", options: ["Режим дозволів", "Модель", "Тему оформлення"], correct: 0, feedback: "Цикл: `default` → `acceptEdits` → `plan` → … Модель — `/model`, тема — `/theme`." },
    { title: "Безпека", question: "Колега радить: «запускай завжди з `--dangerously-skip-permissions`, щоб не клацати „так“». Що відповісти?", options: ["Слушно, так робить більшість", "Це вмикає `bypassPermissions`: агент діє без запитів і перевірок; допустимо лише в контейнері чи VM", "Це безпечно, якщо є `CLAUDE.md`"], correct: 1, feedback: "Для меншої кількості запитів є `acceptEdits`, `auto`, правила allow і `/sandbox`." },
    { title: "Безпека", question: "Як заборонити агенту читати `.env` незалежно від режиму?", options: ["Написати про це в промпті", "Перейменувати файл", "Додати правило deny `Read(./.env)` через `/permissions`"], correct: 2, feedback: "Правила deny діють у кожному режимі, навіть у `bypassPermissions`." },
    { title: "Безпека", question: "Що робить `/sandbox`?", options: ["Вмикає пісочницю, що обмежує доступ команд оболонки до файлів і мережі", "Видаляє тимчасові файли", "Запускає демо-проєкт"], correct: 0, feedback: "Пісочниця обмежує наслідки команд, режим дозволів — чи питати тебе." },
    { title: "Контекст", question: "Контекст заповнений на 85 %, а задача та сама. Що обрати?", options: ["`/compact` з підказкою, що зберегти", "`/clear`", "`/exit`"], correct: 0, feedback: "`/clear` — для нової задачі; `/compact` зберігає суть розмови." },
    { title: "Відкат", question: "Агент зробив невдалу правку `app.js` інструментом редагування. Найшвидший відкат?", options: ["`git reset --hard`", "`/rewind` або `Esc Esc` і відновити код до чекпоінту", "`/clear`"], correct: 1, feedback: "`git reset --hard` знищив би й інші незакомічені зміни; `/clear` файли не чіпає." },
    { title: "Відкат", question: "Чому перед сесією все одно потрібен коміт, хоча є `/rewind`?", options: ["`/rewind` працює лише в хмарі", "Без коміту Claude Code не запускається", "Чекпоінти не відстежують змін від команд оболонки, ручних правок і фонових субагентів"], correct: 2, feedback: "Git — страховка там, де чекпоінти безсилі." },
    { title: "Review", question: "Яка команда шукає вразливості (ін'єкції, обхід автентифікації) у змінах гілки?", options: ["`/security-review`", "`/simplify`", "`/diff`"], correct: 0, feedback: "`/simplify` — про чистоту коду, `/diff` — лише показує зміни." },
    { title: "Review", question: "Тести зелені, але треба переконатися, що застосунок справді працює після зміни. Яка команда?", options: ["`/context`", "`/verify`", "`/usage`"], correct: 1, feedback: "`/verify` збирає, запускає застосунок і перевіряє поведінку." },
    { title: "Модель", question: "Як перемкнутися на актуальну модель Sonnet, не знаючи номера версії?", options: ["`/model sonnet-latest-version`", "`/model claude-sonnet`", "`/model sonnet`"], correct: 2, feedback: "Аліас `sonnet` вказує на актуальну Sonnet твого провайдера." },
    { title: "Витрати", question: "Де подивитися витрати сесії й залишок ліміту плану?", options: ["`/usage` (аліаси `/cost`, `/stats`)", "`/status`", "`/context`"], correct: 0, feedback: "`/status` — версія й акаунт, `/context` — заповнення вікна контексту." },
    { title: "MCP", question: "Сервер `github` у `/mcp` показує failed. Що зробити?", options: ["`/clear`", "`/mcp reconnect github`", "Перевстановити Git"], correct: 1, feedback: "Перепідключення без перезапуску сесії." },
    { title: "Skills", question: "Як зробити власну команду `/release-check` для всієї команди проєкту?", options: ["Створити `.claude/skills/release-check/SKILL.md` у репозиторії", "Написати її в `~/.zshrc`", "Попросити `/init`"], correct: 0, feedback: "Назва теки skill стає командою; проєктна тека доступна всім." },
    { title: "Фон", question: "Ти хочеш залишитися в поточній розмові, а копію агента відправити писати тести у фоні. Яка команда?", options: ["`/background`", "`/tasks`", "`/fork write tests for the auth module`"], correct: 2, feedback: "`/background` від'єднує саму поточну сесію; `/fork` створює фонову копію." }
  ]
};
